export const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEM_FROM_CHECKOUT: 'CLEAR_ITEM_FROM_CHECKOUT',
  CLEAR_CART: 'CLEAR_CART',
  SYNC_CART_SUCCESS: 'SYNC_CART_SUCCESS',
  SYNC_CART_FAILURE: 'SYNC_CART_FAILURE',
  FETCH_CART_SUCCESS: 'FETCH_CART_SUCCESS',
  FETCH_CART_FAILURE: 'FETCH_CART_FAILURE',
};
