const OrderActionTypes = {
  CREATE_ORDER_CREATE: 'CREATE_ORDER_CREATE',
  CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
  CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE',
};

export default OrderActionTypes;
